matrix:
  include:
  - language: python
    python: 3.5
    before_install: cd rekallpy
    install: pip3 install .
    script: python3 setup.py test
    deploy:
      skip_cleanup: true
      provider: pypi
      user: wcrichto
      password:
        secure: H5LU6IZEJpCHpGM+QF2x2G0hMaDNFcvrq/hraIooqe5jwXQzVUPIF1NKEEHZLwsOKJiXdDxntUtVIXq3IuyHPuuIEkp4mb+i4kwjM8XCV59ngGGAfdv/J2ivL4zfqmIrWqwFgQ9/NCQGcsMKkVWWiezsd3QKT3PURHFrW64iwDMGLPxguY02Ymg5J7spwUFuHfknWcIEL7INA8yuhn9xQRmZpToVoDWQiEm7yJK07LbWrh7P1M8m9AqRTfNticutMXZqzFXZFyfkuBo5vedfq2ntM8LojCo2TUDihq+mNiCbzNOanFHdQzRq8hDsQ1MM2G2QlDwmDW2z6vKkXns1E9S+G1bn26ajbfDbHeLUyizpddzwf29qR6V/L3eKGPexnaRNA4/8PJxErHthE3qRtnkcQWmqu9YMPPsIpQielzyRWPL9kaBPOGTMzrmjPOvyeKkm5t3uvJHTVjFZk0ecgWAjZeJTzNDqF+8hO0grpJ2Kqm8l/PQ9InUG09HCpqjOIOn8kwYipLCAdFwgDj1cK4A18Ga9KHZ9jsb7kLSwCE1mk4NEOxT58otIxygrpRv4gIVS+F6ZNixwONKZa8GE2kJRY0cFHKMaz6FrRNhTkRJ0E65miGv4C8wsiv48fVc9lerx5wRpw0SjTwVjOiD61AlnONeTnfyDC1nbwe0eBq0=
      on:
        tags: true
        distributions: sdist bdist_wheel
  - language: node_js
    node_js: 10
    before_install: cd rekalljs
    install: npm install && npm run prepublishOnly
    script: npm run test
    deploy:
      provider: npm
      email: wcrichto@cs.stanford.edu
      api_key:
        secure: QUs06lBFyNUVHh7+ph45dJDeo9drgCWng65UR5jMXcT8u6U1BPsQ1fy0+djAn2X9LL1ZWBJK+H+en17w70xInDUW0tRuI1XJ5SFGm+4J0+mPEisG4gygn7+E6bd1gIBqbxthQPJXIJQ1XZ4zRWZOuDliNVfMAn57SSJClP9kiTzV4U3wUG0uyPtlHNekAh5lw5Qj7SMRs0f9S2bnCIrbecKB7k/Cb/++sni8Umso/V0nOOKT+xZtCRRoQJkIUVtgycIhDrOunMDaPns0bqS0rIi6XiUS7CsFy8RSaOU5z2hDuZllMdFAwdiT6A5RcPRuJqVXf6+g7zmqNqRGmJlKupkCzLCgvV1SiSMKXcv88UmYBfUezhL17BZkMBjYatQL/fzNvrpz9iIlgYjoDBjNrK42rf1MCmu7tm1pUbWXCBu9tNDiWwER+qcHBUasugDQdfPrisDJQQiVpLdw1IXu7oXX+Lv5MRlXzgB0SnmjB5lDLs54BjbAmtsMy850V/APm0+KPkbtoV/1Zd0mEw67Wwq5s7O/BBokOf4wrBeUg6Ujh4/85T3UJ3hJ8bssWllV59MSWcfruGmxuUOF8iuTQDvGBNv9BFZOWvZcrLxqP9wLorEGJ1N/egS/3eFBSL4veWCv8iY4m3un+EI8kvGNSK3SFtMZFXVPPQMr9Fa4h1c=
      skip_cleanup: true
      on:
        tags: true
