name: rekall
channels:
  - conda-forge
  - menpo
  - defaults
dependencies:
  - anaconda
  - python=3.7.3
  - pip=19.0.3
  - ffmpeg
  - nodejs
  - pip:
    - python-constraint==1.4.0
    - rekallpy==0.2.3
    - vgrid-jupyter==0.1.8
    - vgridpy==0.1.7
